import React from 'react';

/**
 * Reusable Rich Text Viewer.
 * Used to safely render HTML content generated by the RichTextEditor.
 */
export default function RichTextViewer({ content, className = '' }) {
  if (!content) return null;

  return (
    <div 
      className={`rich-text-viewer ql-editor ${className}`} 
      dangerouslySetInnerHTML={{ __html: content }} 
    />
  );
}
